AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  UploadToS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 6
      Role: 'arn:aws:iam::557513616795:role/service-role/neptune_access'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /graph
            Method: POST
