AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 5
      Role: 'arn:aws:iam::557513616795:role/service-role/neptune_access'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /graph
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /graph
            Method: OPTIONS
      VpcConfig:
        SecurityGroupIds:
          - sg-033d2770fa31ee62b
        SubnetIds:
          - subnet-0ddb2e51
          - subnet-72a55f15
          - subnet-1309fe3d
          - subnet-54348d1e
          - subnet-78838947
          - subnet-c8d459c7
